name: Check HTTP status

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Vérification toutes les 12 heures

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Path csv file
        run: echo "SITE_CSV=data/site.csv" >> $GITHUB_ENV

      - name: Read site CSV
        run: |
          SITES=$(node site-json.js)
          echo "SITES=$SITES" >> $GITHUB_ENV

      - name: Check http status code of production site
        id: final-result
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '${{ env.SITES }}'
          expected: '[200,200,200,200]'
        continue-on-error: true

      - name: Create issue
        if: failure()
        run: echo "${{ steps.final-result.outputs.status }}"
